name: CI

on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: FOUNDRY_PROFILE=default forge test -vvv --gas-report

  test-zksync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: matter-labs/foundry-zksync
          ref: 'main'
          path: 'foundry-zksync'

      - name: Install Foundry for zksync
        run: ./foundry-zksync/install-foundry-zksync

      - name: Run tests
        run: FOUNDRY_PROFILE=zksync forge test -vvv --zksync

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run coverage
        run: yarn coverage

  coverage-zksync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: matter-labs/foundry-zksync
          ref: 'main'
          path: 'foundry-zksync'

      - name: Install Foundry for zksync
        run: ./foundry-zksync/install-foundry-zksync
      - name: Run coverage
        run: yarn coverage:zksync
